# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: python
        run: python -c "print(1+1)"
        
      - name: Run a one-line scriptenv
        env:
          TEST: aaaa
        run:|
          echo Hello, world!${{secrets.HOST}}
          echo Hello, world!$TEST
          echo Hello, world!${TEST}
          echo Hello, world!${{TEST}}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run a multi-line script
        env:
          SECRET_KEY: ${{ secrets.ID_RSA }}
          USER: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
        run: |
        echo "$SECRET_KEY" > secret_key
        chmod 600 secret_key
        ssh -p ${PORT} -oStrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "cd ~/ && touch hoge"
