# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: scp and ssh
      env:
        SECRET_KEY: ${{ secrets.ID_RSA }}
        USER: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        HOST: ${{ secrets.HOST }}
        DIST: ${{ secrets.PATH_DIST }}
      run: |
        echo "${SECRET_KEY}" > secret_key
        chmod 600 secret_key
        tar zcvf - dist | ssh -p ${PORT} -oStrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "cat > /tmp/dist.tgz && cd ${DIST} && tar xfvz dist.tgz"

        ssh -p ${PORT} -oStrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "/usr/local/bin/azcopy login --identity && /usr/local/bin/azcopy 'sync' --recursive '${DIST}' 'https://slnaviblobstrage.blob.core.windows.net/static/' && sudo service gunicorn restart"

        #ssh -p ${PORT} -oStrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "cd ~/ && touch hoge"
        #scp -P ${PORT} -o StrictHostKeyChecking=no -rp x.py -i secret_key ${USER}@${HOST}:~/
