name: CI/CD pipeline
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (Use Node.js ${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Deploy
      env:
        SECRET_KEY: ${{ secrets.ID_RSA }}
        USER: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        HOST: ${{ secrets.HOST }}
        DIST: ${{ secrets.PATH_DIST }}
      run: |
        echo "${SECRET_KEY}" > secret_key
        chmod 600 secret_key
        tar zcf - dist | ssh -p ${PORT} -oStrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "tar xfz - -C ${DIST}"
      run: ssh -p ${PORT} -oStrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "/usr/local/bin/azcopy login --identity && /usr/local/bin/azcopy 'sync' --recursive '${DIST}/dist/' 'https://slnaviblobstrage.blob.core.windows.net/static/dist/' && sudo service gunicorn restart"
