name: scp test
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      USER: ${{ secrets.USERNAME }}
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
      run: 
        echo "$SECRET_KEY" > secret_key
        chmod 600 secret_key
        ssh -p ${PORT} -oStrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "cd ~/ && touch hoge"
