
name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Operations
      uses: alinz/ssh-scp-action@master
      env:
        HELLO: cool
        MESSAGE: hello world
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.ID_RSA }}
        # runs this on remove server
        ssh_before: |
          touch hoge
          echo $HELLO
          echo $MESSAGE
          echo hoge
          ls -lath
